<?php
/**
 * QcApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TelestreamCloud;

use \TelestreamCloud\Configuration;
use \TelestreamCloud\ApiClient;
use \TelestreamCloud\ApiException;
use \TelestreamCloud\ObjectSerializer;

/**
 * QcApiTest Class Doc Comment
 *
 * @category Class
 * @package  TelestreamCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QcApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelJob
     *
     * .
     *
     */
    public function testCancelJob()
    {
    }

    /**
     * Test case for createJob
     *
     * Create a new job.
     *
     */
    public function testCreateJob()
    {
    }

    /**
     * Test case for createProject
     *
     * Create a new project.
     *
     */
    public function testCreateProject()
    {
    }

    /**
     * Test case for getJob
     *
     * Get QC job.
     *
     */
    public function testGetJob()
    {
    }

    /**
     * Test case for getProject
     *
     * Get project by Id.
     *
     */
    public function testGetProject()
    {
    }

    /**
     * Test case for listJobs
     *
     * Get jobs form projects.
     *
     */
    public function testListJobs()
    {
    }

    /**
     * Test case for listProjects
     *
     * List all projects for an account.
     *
     */
    public function testListProjects()
    {
    }

    /**
     * Test case for modifyProject
     *
     * Modify project.
     *
     */
    public function testModifyProject()
    {
    }

    /**
     * Test case for proxy
     *
     * .
     *
     */
    public function testProxy()
    {
    }

    /**
     * Test case for removeJob
     *
     * .
     *
     */
    public function testRemoveJob()
    {
    }

    /**
     * Test case for removeProject
     *
     * .
     *
     */
    public function testRemoveProject()
    {
    }

    /**
     * Test case for signedUrls
     *
     * .
     *
     */
    public function testSignedUrls()
    {
    }

    /**
     * Test case for uploadVideo
     *
     * Creates an upload session.
     *
     */
    public function testUploadVideo()
    {
    }
}
