<?php
/**
 * CreateVideoBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudFlip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TelestreamCloudFlip;

/**
 * CreateVideoBodyTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateVideoBody
/**
 * @package     TelestreamCloudFlip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateVideoBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateVideoBody"
     */
    public function testCreateVideoBody()
    {
    }

    /**
     * Test attribute "source_url"
     */
    public function testPropertySourceUrl()
    {
    }

    /**
     * Test attribute "profiles"
     */
    public function testPropertyProfiles()
    {
    }

    /**
     * Test attribute "payload"
     */
    public function testPropertyPayload()
    {
    }

    /**
     * Test attribute "pipeline"
     */
    public function testPropertyPipeline()
    {
    }

    /**
     * Test attribute "subtitle_files"
     */
    public function testPropertySubtitleFiles()
    {
    }
}
