<?php
/**
 * FactoryBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudFlip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TelestreamCloudFlip;

/**
 * FactoryBodyTest Class Doc Comment
 *
 * @category    Class */
// * @description FactoryBody
/**
 * @package     TelestreamCloudFlip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FactoryBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FactoryBody"
     */
    public function testFactoryBody()
    {
    }

    /**
     * Test attribute "aws_access_key"
     */
    public function testPropertyAwsAccessKey()
    {
    }

    /**
     * Test attribute "aws_secret_key"
     */
    public function testPropertyAwsSecretKey()
    {
    }

    /**
     * Test attribute "factory_region"
     */
    public function testPropertyFactoryRegion()
    {
    }

    /**
     * Test attribute "input_bucket_file_pattern"
     */
    public function testPropertyInputBucketFilePattern()
    {
    }

    /**
     * Test attribute "input_bucket_name"
     */
    public function testPropertyInputBucketName()
    {
    }

    /**
     * Test attribute "input_bucket_recursive"
     */
    public function testPropertyInputBucketRecursive()
    {
    }

    /**
     * Test attribute "input_bucket_sync_every_n_min"
     */
    public function testPropertyInputBucketSyncEveryNMin()
    {
    }

    /**
     * Test attribute "input_bucket_watch"
     */
    public function testPropertyInputBucketWatch()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "outputs_path_format"
     */
    public function testPropertyOutputsPathFormat()
    {
    }

    /**
     * Test attribute "provider_specific_settings"
     */
    public function testPropertyProviderSpecificSettings()
    {
    }

    /**
     * Test attribute "acl"
     */
    public function testPropertyAcl()
    {
    }

    /**
     * Test attribute "output_bucket_name"
     */
    public function testPropertyOutputBucketName()
    {
    }

    /**
     * Test attribute "server_side_encryption"
     */
    public function testPropertyServerSideEncryption()
    {
    }

    /**
     * Test attribute "storage_credential_attributes"
     */
    public function testPropertyStorageCredentialAttributes()
    {
    }

    /**
     * Test attribute "storage_provider"
     */
    public function testPropertyStorageProvider()
    {
    }
}
