<?php
/**
 * FactoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudFlip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TelestreamCloudFlip;

/**
 * FactoryTest Class Doc Comment
 *
 * @category    Class */
// * @description Factory
/**
 * @package     TelestreamCloudFlip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Factory"
     */
    public function testFactory()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "factory_region"
     */
    public function testPropertyFactoryRegion()
    {
    }

    /**
     * Test attribute "output_bucket_name"
     */
    public function testPropertyOutputBucketName()
    {
    }

    /**
     * Test attribute "acl"
     */
    public function testPropertyAcl()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "server_side_encryption"
     */
    public function testPropertyServerSideEncryption()
    {
    }

    /**
     * Test attribute "input_bucket_name"
     */
    public function testPropertyInputBucketName()
    {
    }

    /**
     * Test attribute "input_bucket_watch"
     */
    public function testPropertyInputBucketWatch()
    {
    }

    /**
     * Test attribute "input_bucket_files_map"
     */
    public function testPropertyInputBucketFilesMap()
    {
    }

    /**
     * Test attribute "input_bucket_sync_every_n_min"
     */
    public function testPropertyInputBucketSyncEveryNMin()
    {
    }

    /**
     * Test attribute "input_bucket_recursive"
     */
    public function testPropertyInputBucketRecursive()
    {
    }

    /**
     * Test attribute "input_bucket_file_pattern"
     */
    public function testPropertyInputBucketFilePattern()
    {
    }

    /**
     * Test attribute "outputs_path_format"
     */
    public function testPropertyOutputsPathFormat()
    {
    }

    /**
     * Test attribute "storage_provider"
     */
    public function testPropertyStorageProvider()
    {
    }

    /**
     * Test attribute "provider_specific_settings"
     */
    public function testPropertyProviderSpecificSettings()
    {
    }
}
