<?php
/**
 * ProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudFlip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TelestreamCloudFlip;

/**
 * ProfileTest Class Doc Comment
 *
 * @category    Class */
// * @description Profile
/**
 * @package     TelestreamCloudFlip
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProfileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Profile"
     */
    public function testProfile()
    {
    }

    /**
     * Test attribute "advanced_fps_conversion"
     */
    public function testPropertyAdvancedFpsConversion()
    {
    }

    /**
     * Test attribute "aspect_mode"
     */
    public function testPropertyAspectMode()
    {
    }

    /**
     * Test attribute "aspect_ratio"
     */
    public function testPropertyAspectRatio()
    {
    }

    /**
     * Test attribute "audio_bitrate"
     */
    public function testPropertyAudioBitrate()
    {
    }

    /**
     * Test attribute "audio_channels"
     */
    public function testPropertyAudioChannels()
    {
    }

    /**
     * Test attribute "audio_channels_layout"
     */
    public function testPropertyAudioChannelsLayout()
    {
    }

    /**
     * Test attribute "audio_channels_per_track"
     */
    public function testPropertyAudioChannelsPerTrack()
    {
    }

    /**
     * Test attribute "audio_codec"
     */
    public function testPropertyAudioCodec()
    {
    }

    /**
     * Test attribute "audio_format"
     */
    public function testPropertyAudioFormat()
    {
    }

    /**
     * Test attribute "audio_map"
     */
    public function testPropertyAudioMap()
    {
    }

    /**
     * Test attribute "audio_pid"
     */
    public function testPropertyAudioPid()
    {
    }

    /**
     * Test attribute "audio_profile"
     */
    public function testPropertyAudioProfile()
    {
    }

    /**
     * Test attribute "audio_sample_rate"
     */
    public function testPropertyAudioSampleRate()
    {
    }

    /**
     * Test attribute "audio_stream_id"
     */
    public function testPropertyAudioStreamId()
    {
    }

    /**
     * Test attribute "audio_streams"
     */
    public function testPropertyAudioStreams()
    {
    }

    /**
     * Test attribute "avcintra_class"
     */
    public function testPropertyAvcintraClass()
    {
    }

    /**
     * Test attribute "buffer_size"
     */
    public function testPropertyBufferSize()
    {
    }

    /**
     * Test attribute "buffer_size_in_packets"
     */
    public function testPropertyBufferSizeInPackets()
    {
    }

    /**
     * Test attribute "bumpers"
     */
    public function testPropertyBumpers()
    {
    }

    /**
     * Test attribute "byte_range_requests"
     */
    public function testPropertyByteRangeRequests()
    {
    }

    /**
     * Test attribute "clip_length"
     */
    public function testPropertyClipLength()
    {
    }

    /**
     * Test attribute "clip_offset"
     */
    public function testPropertyClipOffset()
    {
    }

    /**
     * Test attribute "closed_captions"
     */
    public function testPropertyClosedCaptions()
    {
    }

    /**
     * Test attribute "color_metadata"
     */
    public function testPropertyColorMetadata()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "crop_input_bottom"
     */
    public function testPropertyCropInputBottom()
    {
    }

    /**
     * Test attribute "crop_input_height"
     */
    public function testPropertyCropInputHeight()
    {
    }

    /**
     * Test attribute "crop_input_left"
     */
    public function testPropertyCropInputLeft()
    {
    }

    /**
     * Test attribute "crop_input_right"
     */
    public function testPropertyCropInputRight()
    {
    }

    /**
     * Test attribute "crop_input_top"
     */
    public function testPropertyCropInputTop()
    {
    }

    /**
     * Test attribute "crop_input_width"
     */
    public function testPropertyCropInputWidth()
    {
    }

    /**
     * Test attribute "dash_profile"
     */
    public function testPropertyDashProfile()
    {
    }

    /**
     * Test attribute "deinterlace"
     */
    public function testPropertyDeinterlace()
    {
    }

    /**
     * Test attribute "deinterlace_frames"
     */
    public function testPropertyDeinterlaceFrames()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "dnxhd_type"
     */
    public function testPropertyDnxhdType()
    {
    }

    /**
     * Test attribute "encryption"
     */
    public function testPropertyEncryption()
    {
    }

    /**
     * Test attribute "extname"
     */
    public function testPropertyExtname()
    {
    }

    /**
     * Test attribute "fps"
     */
    public function testPropertyFps()
    {
    }

    /**
     * Test attribute "frame_count"
     */
    public function testPropertyFrameCount()
    {
    }

    /**
     * Test attribute "frame_interval"
     */
    public function testPropertyFrameInterval()
    {
    }

    /**
     * Test attribute "frame_offsets"
     */
    public function testPropertyFrameOffsets()
    {
    }

    /**
     * Test attribute "h264_level"
     */
    public function testPropertyH264Level()
    {
    }

    /**
     * Test attribute "h264_profile"
     */
    public function testPropertyH264Profile()
    {
    }

    /**
     * Test attribute "h264_tune"
     */
    public function testPropertyH264Tune()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "imx_type"
     */
    public function testPropertyImxType()
    {
    }

    /**
     * Test attribute "inputs"
     */
    public function testPropertyInputs()
    {
    }

    /**
     * Test attribute "interlace"
     */
    public function testPropertyInterlace()
    {
    }

    /**
     * Test attribute "keyframe_interval"
     */
    public function testPropertyKeyframeInterval()
    {
    }

    /**
     * Test attribute "keyframe_rate"
     */
    public function testPropertyKeyframeRate()
    {
    }

    /**
     * Test attribute "lang"
     */
    public function testPropertyLang()
    {
    }

    /**
     * Test attribute "max_rate"
     */
    public function testPropertyMaxRate()
    {
    }

    /**
     * Test attribute "merge_audio_streams"
     */
    public function testPropertyMergeAudioStreams()
    {
    }

    /**
     * Test attribute "mute_audio_tracks"
     */
    public function testPropertyMuteAudioTracks()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "outputs"
     */
    public function testPropertyOutputs()
    {
    }

    /**
     * Test attribute "outputs_path_format"
     */
    public function testPropertyOutputsPathFormat()
    {
    }

    /**
     * Test attribute "playlist_type"
     */
    public function testPropertyPlaylistType()
    {
    }

    /**
     * Test attribute "pmt_pid"
     */
    public function testPropertyPmtPid()
    {
    }

    /**
     * Test attribute "preset_name"
     */
    public function testPropertyPresetName()
    {
    }

    /**
     * Test attribute "prores_format"
     */
    public function testPropertyProresFormat()
    {
    }

    /**
     * Test attribute "segment_time"
     */
    public function testPropertySegmentTime()
    {
    }

    /**
     * Test attribute "stack"
     */
    public function testPropertyStack()
    {
    }

    /**
     * Test attribute "telestream_block_size"
     */
    public function testPropertyTelestreamBlockSize()
    {
    }

    /**
     * Test attribute "telestream_blur_scaler"
     */
    public function testPropertyTelestreamBlurScaler()
    {
    }

    /**
     * Test attribute "telestream_cost_scaler"
     */
    public function testPropertyTelestreamCostScaler()
    {
    }

    /**
     * Test attribute "telestream_search_length_scaler"
     */
    public function testPropertyTelestreamSearchLengthScaler()
    {
    }

    /**
     * Test attribute "telestream_subpel_mode"
     */
    public function testPropertyTelestreamSubpelMode()
    {
    }

    /**
     * Test attribute "time_code"
     */
    public function testPropertyTimeCode()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "trailers"
     */
    public function testPropertyTrailers()
    {
    }

    /**
     * Test attribute "transport_rate"
     */
    public function testPropertyTransportRate()
    {
    }

    /**
     * Test attribute "ts_pids"
     */
    public function testPropertyTsPids()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "upscale"
     */
    public function testPropertyUpscale()
    {
    }

    /**
     * Test attribute "use_editlist"
     */
    public function testPropertyUseEditlist()
    {
    }

    /**
     * Test attribute "variants"
     */
    public function testPropertyVariants()
    {
    }

    /**
     * Test attribute "video_bitrate"
     */
    public function testPropertyVideoBitrate()
    {
    }

    /**
     * Test attribute "video_pid"
     */
    public function testPropertyVideoPid()
    {
    }

    /**
     * Test attribute "watermark_bottom"
     */
    public function testPropertyWatermarkBottom()
    {
    }

    /**
     * Test attribute "watermark_bumpers"
     */
    public function testPropertyWatermarkBumpers()
    {
    }

    /**
     * Test attribute "watermark_height"
     */
    public function testPropertyWatermarkHeight()
    {
    }

    /**
     * Test attribute "watermark_left"
     */
    public function testPropertyWatermarkLeft()
    {
    }

    /**
     * Test attribute "watermark_right"
     */
    public function testPropertyWatermarkRight()
    {
    }

    /**
     * Test attribute "watermark_top"
     */
    public function testPropertyWatermarkTop()
    {
    }

    /**
     * Test attribute "watermark_trailers"
     */
    public function testPropertyWatermarkTrailers()
    {
    }

    /**
     * Test attribute "watermark_url"
     */
    public function testPropertyWatermarkUrl()
    {
    }

    /**
     * Test attribute "watermark_width"
     */
    public function testPropertyWatermarkWidth()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "x264_options"
     */
    public function testPropertyX264Options()
    {
    }

    /**
     * Test attribute "x265_options"
     */
    public function testPropertyX265Options()
    {
    }

    /**
     * Test attribute "xdcam_format"
     */
    public function testPropertyXdcamFormat()
    {
    }

    /**
     * Test attribute "tachyon_allow_remove_pulldown"
     */
    public function testPropertyTachyonAllowRemovePulldown()
    {
    }

    /**
     * Test attribute "tachyon_enable_post_pulldown_filter"
     */
    public function testPropertyTachyonEnablePostPulldownFilter()
    {
    }

    /**
     * Test attribute "tachyon_media_hint_is_cartoon"
     */
    public function testPropertyTachyonMediaHintIsCartoon()
    {
    }

    /**
     * Test attribute "tachyon_media_hint_has_chroma_noise"
     */
    public function testPropertyTachyonMediaHintHasChromaNoise()
    {
    }

    /**
     * Test attribute "tachyon_more_sensitive_remove_pulldown"
     */
    public function testPropertyTachyonMoreSensitiveRemovePulldown()
    {
    }

    /**
     * Test attribute "tachyon_allow_add_standard_pd"
     */
    public function testPropertyTachyonAllowAddStandardPd()
    {
    }

    /**
     * Test attribute "tachyon_allow_add_2_2pd"
     */
    public function testPropertyTachyonAllowAdd22pd()
    {
    }

    /**
     * Test attribute "tachyon_allow_add_4_4pd"
     */
    public function testPropertyTachyonAllowAdd44pd()
    {
    }

    /**
     * Test attribute "tachyon_allow_add_4_6pd"
     */
    public function testPropertyTachyonAllowAdd46pd()
    {
    }

    /**
     * Test attribute "tachyon_allow_add_euro_pd"
     */
    public function testPropertyTachyonAllowAddEuroPd()
    {
    }

    /**
     * Test attribute "tachyon_allow_add_adaptive_pd"
     */
    public function testPropertyTachyonAllowAddAdaptivePd()
    {
    }

    /**
     * Test attribute "tachyon_motion_amount"
     */
    public function testPropertyTachyonMotionAmount()
    {
    }

    /**
     * Test attribute "tachyon_fallback_size"
     */
    public function testPropertyTachyonFallbackSize()
    {
    }

    /**
     * Test attribute "tachyon_mblock_size"
     */
    public function testPropertyTachyonMblockSize()
    {
    }

    /**
     * Test attribute "tachyon_cut_detection_sensitivity"
     */
    public function testPropertyTachyonCutDetectionSensitivity()
    {
    }

    /**
     * Test attribute "eac3_evolution_enable"
     */
    public function testPropertyEac3EvolutionEnable()
    {
    }

    /**
     * Test attribute "eac3_bitstream_mode"
     */
    public function testPropertyEac3BitstreamMode()
    {
    }

    /**
     * Test attribute "eac3_ninety_degree_phase_shift"
     */
    public function testPropertyEac3NinetyDegreePhaseShift()
    {
    }

    /**
     * Test attribute "eac3_three_decibel_attenuation"
     */
    public function testPropertyEac3ThreeDecibelAttenuation()
    {
    }

    /**
     * Test attribute "eac3_enable_lfe_low_pass_filter"
     */
    public function testPropertyEac3EnableLfeLowPassFilter()
    {
    }

    /**
     * Test attribute "eac3_analog_to_digital_converter_type"
     */
    public function testPropertyEac3AnalogToDigitalConverterType()
    {
    }

    /**
     * Test attribute "eac3_stereo_downmix_preference"
     */
    public function testPropertyEac3StereoDownmixPreference()
    {
    }

    /**
     * Test attribute "eac3_lt_rt_center_mix_level"
     */
    public function testPropertyEac3LtRtCenterMixLevel()
    {
    }

    /**
     * Test attribute "eac3_lt_rt_surround_mix_level"
     */
    public function testPropertyEac3LtRtSurroundMixLevel()
    {
    }

    /**
     * Test attribute "eac3_lo_ro_center_mix_level"
     */
    public function testPropertyEac3LoRoCenterMixLevel()
    {
    }

    /**
     * Test attribute "eac3_lo_ro_surround_mix_level"
     */
    public function testPropertyEac3LoRoSurroundMixLevel()
    {
    }

    /**
     * Test attribute "eac3_surround_ex_mode"
     */
    public function testPropertyEac3SurroundExMode()
    {
    }

    /**
     * Test attribute "eac3_drc_line_mode_profile"
     */
    public function testPropertyEac3DrcLineModeProfile()
    {
    }

    /**
     * Test attribute "eac3_drc_rf_mode_profile"
     */
    public function testPropertyEac3DrcRfModeProfile()
    {
    }

    /**
     * Test attribute "eac3_dialog_normalization"
     */
    public function testPropertyEac3DialogNormalization()
    {
    }

    /**
     * Test attribute "eac3_room_type"
     */
    public function testPropertyEac3RoomType()
    {
    }

    /**
     * Test attribute "eac3_mixing_level"
     */
    public function testPropertyEac3MixingLevel()
    {
    }

    /**
     * Test attribute "eac3_copyright_protected"
     */
    public function testPropertyEac3CopyrightProtected()
    {
    }

    /**
     * Test attribute "eac3_original_bitstream"
     */
    public function testPropertyEac3OriginalBitstream()
    {
    }
}
