<?php
/**
 * VideoUploadBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TelestreamCloud;

/**
 * VideoUploadBodyTest Class Doc Comment
 *
 * @category    Class */
// * @description VideoUploadBody
/**
 * @package     TelestreamCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VideoUploadBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VideoUploadBody"
     */
    public function testVideoUploadBody()
    {
    }

    /**
     * Test attribute "file_size"
     */
    public function testPropertyFileSize()
    {
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
    }

    /**
     * Test attribute "extra_files"
     */
    public function testPropertyExtraFiles()
    {
    }

    /**
     * Test attribute "profiles"
     */
    public function testPropertyProfiles()
    {
    }

    /**
     * Test attribute "path_format"
     */
    public function testPropertyPathFormat()
    {
    }

    /**
     * Test attribute "payload"
     */
    public function testPropertyPayload()
    {
    }

    /**
     * Test attribute "extra_variables"
     */
    public function testPropertyExtraVariables()
    {
    }

    /**
     * Test attribute "watermark_url"
     */
    public function testPropertyWatermarkUrl()
    {
    }

    /**
     * Test attribute "watermark_left"
     */
    public function testPropertyWatermarkLeft()
    {
    }

    /**
     * Test attribute "watermark_top"
     */
    public function testPropertyWatermarkTop()
    {
    }

    /**
     * Test attribute "watermark_right"
     */
    public function testPropertyWatermarkRight()
    {
    }

    /**
     * Test attribute "watermark_bottom"
     */
    public function testPropertyWatermarkBottom()
    {
    }

    /**
     * Test attribute "watermark_width"
     */
    public function testPropertyWatermarkWidth()
    {
    }

    /**
     * Test attribute "watermark_height"
     */
    public function testPropertyWatermarkHeight()
    {
    }

    /**
     * Test attribute "clip_length"
     */
    public function testPropertyClipLength()
    {
    }

    /**
     * Test attribute "clip_offset"
     */
    public function testPropertyClipOffset()
    {
    }

    /**
     * Test attribute "multi_chunk"
     */
    public function testPropertyMultiChunk()
    {
    }
}
