<?php
/**
 * UploadSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudQc
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TelestreamCloudQc;

/**
 * UploadSessionTest Class Doc Comment
 *
 * @category    Class */
// * @description UploadSession
/**
 * @package     TelestreamCloudQc
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UploadSessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UploadSession"
     */
    public function testUploadSession()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "parts"
     */
    public function testPropertyParts()
    {
    }

    /**
     * Test attribute "part_size"
     */
    public function testPropertyPartSize()
    {
    }

    /**
     * Test attribute "max_connections"
     */
    public function testPropertyMaxConnections()
    {
    }

    /**
     * Test attribute "extra_files"
     */
    public function testPropertyExtraFiles()
    {
    }
}
