<?php
/**
 * NotificationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudNotifications
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Notifications API
 *
 * Notifications API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TelestreamCloudNotifications;

use \TelestreamCloudNotifications\Configuration;
use \TelestreamCloudNotifications\ApiException;
use \TelestreamCloudNotifications\ObjectSerializer;

/**
 * NotificationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  TelestreamCloudNotifications
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NotificationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSubscription
     *
     * Create a new subscription.
     *
     */
    public function testCreateSubscription()
    {
    }

    /**
     * Test case for deleteSubscription
     *
     * .
     *
     */
    public function testDeleteSubscription()
    {
    }

    /**
     * Test case for listSubscriptions
     *
     * .
     *
     */
    public function testListSubscriptions()
    {
    }
}
