<?php
/**
 * CloudNotificationSettingsEvents
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloud
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TelestreamCloud\Flip;

use \ArrayAccess;

/**
 * CloudNotificationSettingsEvents Class Doc Comment
 *
 * @category    Class
 * @package     TelestreamCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CloudNotificationSettingsEvents implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CloudNotificationSettings_events';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'encoding_completed' => 'bool',
        'encoding_progress' => 'bool',
        'video_created' => 'bool',
        'video_encoded' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'encoding_completed' => null,
        'encoding_progress' => null,
        'video_created' => null,
        'video_encoded' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'encoding_completed' => 'encoding_completed',
        'encoding_progress' => 'encoding_progress',
        'video_created' => 'video_created',
        'video_encoded' => 'video_encoded'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'encoding_completed' => 'setEncodingCompleted',
        'encoding_progress' => 'setEncodingProgress',
        'video_created' => 'setVideoCreated',
        'video_encoded' => 'setVideoEncoded'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'encoding_completed' => 'getEncodingCompleted',
        'encoding_progress' => 'getEncodingProgress',
        'video_created' => 'getVideoCreated',
        'video_encoded' => 'getVideoEncoded'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['encoding_completed'] = isset($data['encoding_completed']) ? $data['encoding_completed'] : null;
        $this->container['encoding_progress'] = isset($data['encoding_progress']) ? $data['encoding_progress'] : null;
        $this->container['video_created'] = isset($data['video_created']) ? $data['video_created'] : null;
        $this->container['video_encoded'] = isset($data['video_encoded']) ? $data['video_encoded'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['encoding_completed'] === null) {
            $invalid_properties[] = "'encoding_completed' can't be null";
        }
        if ($this->container['encoding_progress'] === null) {
            $invalid_properties[] = "'encoding_progress' can't be null";
        }
        if ($this->container['video_created'] === null) {
            $invalid_properties[] = "'video_created' can't be null";
        }
        if ($this->container['video_encoded'] === null) {
            $invalid_properties[] = "'video_encoded' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['encoding_completed'] === null) {
            return false;
        }
        if ($this->container['encoding_progress'] === null) {
            return false;
        }
        if ($this->container['video_created'] === null) {
            return false;
        }
        if ($this->container['video_encoded'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets encoding_completed
     * @return bool
     */
    public function getEncodingCompleted()
    {
        return $this->container['encoding_completed'];
    }

    /**
     * Sets encoding_completed
     * @param bool $encoding_completed If set to `true`, a notification will be sent after an encoding becomes complete.
     * @return $this
     */
    public function setEncodingCompleted($encoding_completed)
    {
        $this->container['encoding_completed'] = $encoding_completed;

        return $this;
    }

    /**
     * Gets encoding_progress
     * @return bool
     */
    public function getEncodingProgress()
    {
        return $this->container['encoding_progress'];
    }

    /**
     * Sets encoding_progress
     * @param bool $encoding_progress If set to `true`, a notification will be sent after an encoding's progess changes.
     * @return $this
     */
    public function setEncodingProgress($encoding_progress)
    {
        $this->container['encoding_progress'] = $encoding_progress;

        return $this;
    }

    /**
     * Gets video_created
     * @return bool
     */
    public function getVideoCreated()
    {
        return $this->container['video_created'];
    }

    /**
     * Sets video_created
     * @param bool $video_created If set to `true`, a notification will be sent after a video is created.
     * @return $this
     */
    public function setVideoCreated($video_created)
    {
        $this->container['video_created'] = $video_created;

        return $this;
    }

    /**
     * Gets video_encoded
     * @return bool
     */
    public function getVideoEncoded()
    {
        return $this->container['video_encoded'];
    }

    /**
     * Sets video_encoded
     * @param bool $video_encoded If set to `true`, a notification will be sent after a video is encoded.
     * @return $this
     */
    public function setVideoEncoded($video_encoded)
    {
        $this->container['video_encoded'] = $video_encoded;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\TelestreamCloud\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\TelestreamCloud\ObjectSerializer::sanitizeForSerialization($this));
    }
}


