<?php
/**
 * FragmentVariantTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudTts
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Tts API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TelestreamCloudTts;

/**
 * FragmentVariantTest Class Doc Comment
 *
 * @category    Class */
// * @description FragmentVariant
/**
 * @package     TelestreamCloudTts
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FragmentVariantTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FragmentVariant"
     */
    public function testFragmentVariant()
    {
    }

    /**
     * Test attribute "fragment"
     */
    public function testPropertyFragment()
    {
    }

    /**
     * Test attribute "confidence"
     */
    public function testPropertyConfidence()
    {
    }
}
