<?php
/**
 * FlipApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TelestreamCloudFlip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TelestreamCloudFlip;

use \TelestreamCloudFlip\Configuration;
use \TelestreamCloudFlip\ApiException;
use \TelestreamCloudFlip\ObjectSerializer;

/**
 * FlipApiTest Class Doc Comment
 *
 * @category Class
 * @package  TelestreamCloudFlip
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FlipApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelEncoding
     *
     * Cancels an Encoding..
     *
     */
    public function testCancelEncoding()
    {
    }

    /**
     * Test case for copyProfile
     *
     * Copies a given Profile.
     *
     */
    public function testCopyProfile()
    {
    }

    /**
     * Test case for createEncoding
     *
     * Creates an Encoding.
     *
     */
    public function testCreateEncoding()
    {
    }

    /**
     * Test case for createFactory
     *
     * Creates a new factory.
     *
     */
    public function testCreateFactory()
    {
    }

    /**
     * Test case for createProfile
     *
     * Creates a Profile.
     *
     */
    public function testCreateProfile()
    {
    }

    /**
     * Test case for createVideo
     *
     * Creates a Video from a provided source_url..
     *
     */
    public function testCreateVideo()
    {
    }

    /**
     * Test case for createWorkorder
     *
     * Creates a Workorder..
     *
     */
    public function testCreateWorkorder()
    {
    }

    /**
     * Test case for deleteEncoding
     *
     * Deletes an Encoding from both Telestream Cloud and your storage. Returns an information whether the operation was successful..
     *
     */
    public function testDeleteEncoding()
    {
    }

    /**
     * Test case for deleteProfile
     *
     * Deletes a given Profile.
     *
     */
    public function testDeleteProfile()
    {
    }

    /**
     * Test case for deleteVideo
     *
     * Deletes a Video object..
     *
     */
    public function testDeleteVideo()
    {
    }

    /**
     * Test case for deleteVideoSource
     *
     * Delete a video's source file..
     *
     */
    public function testDeleteVideoSource()
    {
    }

    /**
     * Test case for encoding
     *
     * Returns an Encoding object..
     *
     */
    public function testEncoding()
    {
    }

    /**
     * Test case for encodings
     *
     * Returns a list of Encoding objects.
     *
     */
    public function testEncodings()
    {
    }

    /**
     * Test case for encodingsCount
     *
     * Returns a number of Encoding objects created using a given factory..
     *
     */
    public function testEncodingsCount()
    {
    }

    /**
     * Test case for factories
     *
     * Returns a collection of Factory objects..
     *
     */
    public function testFactories()
    {
    }

    /**
     * Test case for factory
     *
     * Returns a Factory object..
     *
     */
    public function testFactory()
    {
    }

    /**
     * Test case for notifications
     *
     * Returns a Factory's notification settings..
     *
     */
    public function testNotifications()
    {
    }

    /**
     * Test case for profile
     *
     * Returns a Profile object..
     *
     */
    public function testProfile()
    {
    }

    /**
     * Test case for profileEncodings
     *
     * Returns a list of Encodings that belong to a Profile..
     *
     */
    public function testProfileEncodings()
    {
    }

    /**
     * Test case for profiles
     *
     * Returns a collection of Profile objects..
     *
     */
    public function testProfiles()
    {
    }

    /**
     * Test case for queuedVideos
     *
     * Returns a collection of Video objects queued for encoding..
     *
     */
    public function testQueuedVideos()
    {
    }

    /**
     * Test case for resubmitVideo
     *
     * Resubmits a video to encode..
     *
     */
    public function testResubmitVideo()
    {
    }

    /**
     * Test case for retryEncoding
     *
     * Retries a failed encoding..
     *
     */
    public function testRetryEncoding()
    {
    }

    /**
     * Test case for signedEncodingUrl
     *
     * Returns a signed url pointing to an Encoding..
     *
     */
    public function testSignedEncodingUrl()
    {
    }

    /**
     * Test case for signedEncodingUrls
     *
     * Returns a list of signed urls pointing to an Encoding's outputs..
     *
     */
    public function testSignedEncodingUrls()
    {
    }

    /**
     * Test case for signedVideoUrl
     *
     * Returns a signed url pointing to a Video..
     *
     */
    public function testSignedVideoUrl()
    {
    }

    /**
     * Test case for toggleFactorySync
     *
     * Toggles synchronisation settings..
     *
     */
    public function testToggleFactorySync()
    {
    }

    /**
     * Test case for updateEncoding
     *
     * Updates an Encoding.
     *
     */
    public function testUpdateEncoding()
    {
    }

    /**
     * Test case for updateFactory
     *
     * Updates a Factory's settings. Returns a Factory object..
     *
     */
    public function testUpdateFactory()
    {
    }

    /**
     * Test case for updateNotifications
     *
     * Updates a Factory's notification settings..
     *
     */
    public function testUpdateNotifications()
    {
    }

    /**
     * Test case for updateProfile
     *
     * Updates a given Profile.
     *
     */
    public function testUpdateProfile()
    {
    }

    /**
     * Test case for uploadVideo
     *
     * Creates an upload session..
     *
     */
    public function testUploadVideo()
    {
    }

    /**
     * Test case for video
     *
     * Returns a Video object..
     *
     */
    public function testVideo()
    {
    }

    /**
     * Test case for videoEncodings
     *
     * Returns a list of Encodings that belong to a Video..
     *
     */
    public function testVideoEncodings()
    {
    }

    /**
     * Test case for videoMetadata
     *
     * Returns a Video's metadata.
     *
     */
    public function testVideoMetadata()
    {
    }

    /**
     * Test case for videos
     *
     * Returns a collection of Video objects..
     *
     */
    public function testVideos()
    {
    }

    /**
     * Test case for workflows
     *
     * Returns a collection of Workflows that belong to a Factory..
     *
     */
    public function testWorkflows()
    {
    }
}
